### ISSUE TITLE
Will the code dataset be public?

### ISSUE THREAD

**Issue by AceCHQ** [veronica320/Faithful-COT#3]
Hello, Thank you for your excellent job. I noticed that you released some datasets but they were public before. Can you release the dataset with code like the ones in your paper? Thank you.

**Comment by veronica320** [comment]
Hi, thanks for your interest! I'm not sure which datasets you are referring to. To clarify, we didn't create any new dataset in our work, but only used existing ones that can be found under the [`data/`](https://github.com/veronica320/Faithful-COT/tree/main/data) folder.
