### ISSUE TITLE
PDDL domain file

### ISSUE THREAD

**Issue by Martin36** [veronica320/Faithful-COT#4]
I am curious to know how the PDDL domain file looks like for the planning part of your work. I can't seem to find it in the repo. Maybe the domain is part of the original SayCan dataset, but I couldn't find it there either. Is it possible for you to upload the PDDL domain file to this repo?

**Comment by veronica320** [comment]
You can find it here: https://github.com/veronica320/Faithful-COT/blob/main/source/model/solver/saycan/pddl_files/domain/domain.pddl
